version: '3.5'
services:
  webserver:
    container_name: webserver
    image: jc21/nginx-proxy-manager:${WEBSERVER_VERSION}
    restart: always
    ports:
      - ${WEBSERVER_HTTP_PORT}:80
      - ${WEBSERVER_HTTPS_PORT}:443
      - ${WEBSERVER_ADMIN_PORT}:81
    depends_on:
      - php
    links:
      - php
    volumes:
      - ${APP_ROOT_PATH}${WEBSITE_PATH}:/site:ro
      - ${APP_ROOT_PATH}${WEBSERVER_CONF_FILE}:/app/config/production.json
      - ${APP_ROOT_PATH}${WEBSERVER_DATA_DIR}:/data
      - ${APP_ROOT_PATH}${WEBSERVER_CERT_DIR}:/etc/letsencrypt
      - ${APP_ROOT_PATH}${WEBSERVER_REWRITE_DIR}:/rewrite:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    networks:
      - external_network
      # 可以把-external_network 改成下列配置，以固定容器IP
      #- external_network:
      #  ipv4_address: 10.0.0.10
      - internal_network

  php:
    container_name: php
    image: suyar/php:8.2-fpm-alpine
    #image: php-build:8.1-fpm
    #build:
    #  context: ./php
    #  dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${APP_ROOT_PATH}${WEBSITE_PATH}:/site
      - ${APP_ROOT_PATH}${PHP_INI_FILE}:/usr/local/etc/php/php.ini:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    user: "1000:1000"
    ports:
      - ${DATABASE_PORT}:9000
    expose:
      - 9000
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    networks:
      - internal_network

  database:
    container_name: database
    image: ${DATABASE}:${DATABASE_VERSION}
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:3306
    expose:
      - 3306
    environment:
      - "MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    volumes:
      - "${APP_ROOT_PATH}${DATABASE_DATA_DIR}:/var/lib/mysql"
      - "${APP_ROOT_PATH}${DATABASE_CONF_DIR}:/etc/mysql/conf.d"
      - ./mariadb/log:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal_network

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - ${REDIS_PORT}:6389
    expose:
      - 6389
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ${APP_ROOT_PATH}${REDIS_DATA_DIR}:/data
      #- ${APP_ROOT_PATH}${REDIS_CONF_FILE}:/usr/local/etc/redis/custom.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal_network

networks:
  #当前网桥用于向主机外公开
  external_network:
    name: external_network
    driver: bridge
    ipam:
      driver: default
      # 解除下面的注释可以设置网段，用于nginx等容器固定容器IP
      #config:
      #  - subnet: 10.0.0.0/24
  #当前网桥用于将网络限制在本地
  internal_network:
    internal: true